source "http://rubygems.org"

gem "cancan"
gem "devise", "1.1.7"
gem "formtastic"
gem "googlecharts", :require => "gchart"
gem "haml"
gem "haml-rails"
gem "jammit"
gem "jquery-rails"
gem "kaminari"
gem "mysql2", "0.2.6"
gem "rails", "3.0.4"
gem "rails3-generators"
gem "sass"
gem "to-csv", :require => "to_csv"

group :test, :development do
  gem "fabrication"
  gem "faker"
  gem "mocha"
  gem "nifty-generators"
  gem "rspec-rails", "~> 2.4"
  gem "shoulda-matchers"
end
