embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery.min.js
    - public/javascripts/rails.js
    - public/protovis-3.2/protovis-r3.2.js

stylesheets:
  main:
    - public/stylesheets/reset.css
    - public/stylesheets/grid.css
    - public/stylesheets/common.css
    - public/stylesheets/form.css
    - public/stylesheets/application.css
